# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqOKDJNspnqbPCVq_jaaCF1asF5S-76b
"""

import pandas as pd
import requests
import json
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches #to draw random shape in chart
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print("libraries installed")
print(f"pandas version : {pd.__version__}")
print(f"loaded at : {datetime.now().strftime('%Y %m %d %H:%M')}" )

raw_df=pd.read_csv('messy_sales_data.csv')
print(f"Rows : {raw_df.shape[0]}")
print(f"Columns : {raw_df.shape[1]}")
print(f"Columns names : {raw_df.columns.to_list()}")

print("\n[1]missig values")
print(raw_df.isnull().sum())

print(f"\n[2]duplicate rows : {raw_df.duplicated().sum()}")

print(f"\n[3]data types : ")
print(raw_df.dtypes)

print(f"\n[4] unique categoreis : {raw_df['category'].dropna().unique().tolist()}")
print(f"\n[4] sample order : {raw_df['order_date'].unique()[:8].tolist()}")
print(f"\n[4] sample name : {raw_df['customer_name'].unique()[:8].tolist()}")

tf=raw_df.copy()

print(f"copy data shape {tf.shape}")

print("copied raw data")

#total missng value before the fix
print(f"total missing value : {tf.isnull().sum().sum()}")

#fillna replace the null value or nan with str unknown customer , inplace directly make the chnages into df
tf['customer_name'].fillna('unknown customer', inplace=True)

#fix for missing qty , median takes middle val of column , fillna replace the null value with median value
median_qty=rf['quantity'].median()
tf['quantity'].fillna(median_qty, inplace=True)
print(f"filled missing value with median value : {median_qty}")

#
tf['category'].fillna('uncategorized',inplace=True)

#

tf['product'].fillna('unknown product',inplace=True)

print(f"total missing values after fix: {tf.isnull().sum().sum()}")

print(f"rows before duplication: {len(tf)}")

print(f"duplicate row found : {tf.duplicated().sum()}")

duplicate_mask = tf.duplicated(keep=False)  #
print("\nthe duplicated rows(all copies) : ")
print(tf[duplicate_mask][['order_id','customer_name','product','order_date']].to_string(index=False))

#dd-mm-yyyy , mm-dd-yyyy , yyyy-mm-dd

print("sample data bedfore parsing : ")
print(tf['order_date'].head(10).tolist())

tf['order_date']=pd.to_datetime(tf['order_date'],dayfirst=False, errors='coerce')

nat_mask=tf['order_date'].isnull()

tf.loc[nat_mask,'order_date']=pd.to_datetime(raw_df.loc[nat_mask,'order_date'],dayfirst=True,errors='coerce')

nat_count=tf['order_date'].isnull().sum()

print(f"\nunparsable dates remaining (nat) : {nat_count}")


tf['year']=tf['order_date'].dt.year
tf['month']=tf['order_date'].dt.month
tf['month_name']=tf['order_date'].dt.strftime('%B')
tf['day_name']=tf['order_date'].dt.strftime('%A')

print(f"\nsample dates after parsing : ")
print(tf[['order_date','year','month','month_name','day_name']].head(10).to_string())

print("name before standardization: ")
print(tf['customer_name'].unique()[:8].tolist())

tf['customer_name']=tf['customer_name'].str.strip().str.title()

print("\nname after standardization: ")
print(tf['customer_name'].unique()[:8].tolist())

wrong_mask=(tf['product'] == 'Keyboard') & (tf['category'] == 'Electronics')
print(f"rows to fix : {wrong_mask.sum()}")

print("before fix : ")
print(tf[wrong_mask][['order_id','product','category']].to_string(index=False))

print("after fix : ")
tf.loc[wrong_mask,'category']='Accessories'
print(tf[wrong_mask][['order_id','product','category']].to_string(index=False))

tf['quantity']=pd.to_numeric(tf['quantity'],errors='coerce').astype(int)
tf['unit_price']=pd.to_numeric(tf['unit_price'],errors='coerce')

tf['revenue']=tf['quantity'] * tf['unit_price']

print("revenue column created")
print("\nsample: quantity x unitprice = revenue")
print(tf[['customer_name','product','quantity','unit_price','revenue']].head(8).to_string(index=False))

missing_count = tf.isnull().sum().sum()

duplicate_count = tf.duplicated().sum()

date_nulls = tf['order_date'].isnull().sum()

revenue_nulls = tf['revenue'].isnull().sum()

checks_passed = sum([
    missing_count == 0,
    duplicate_count == 0,
    date_nulls == 0,
    revenue_nulls == 0,
    len(tf) > 0
])

quality_score = checks_passed * 20

print(f"Data Quality Score: {quality_score}/100")

output_filename = 'clean_sales_data.csv'

tf.to_csv(output_filename, index=False)

print(f"Cleaned data saved to: {output_filename}")

print(f"Final dataset: {tf.shape[0]} rows x {tf.shape[1]} columns")
output_filename = 'clean_sales_data.csv'

tf.to_csv(output_filename, index=False)

print(f"Cleaned data saved to: {output_filename}")

print(f"Final dataset: {tf.shape[0]} rows x {tf.shape[1]} columns")

print("\nETL Pipeline for Sales Data: COMPLETE")

print("  Extract   → messy_sales_data.csv loaded")

print("  Transform → issues fixed (nulls, dupes, dates, names, categories, types)")

print("  Load      → clean_sales_data.csv saved")

SERP_API_KEY="83ef62e3e4d23c549d97c1925fb38716f08b7a49afce20d039cd21e8cb762509"

SERP_URL="https://serpapi.com/search.json"

SEARCH_QUERY="Data Engineer India"

print(f"SerpAPI Key  : {'Set (live data)' if SERP_API_KEY != 'YOUR_API_KEY' else 'Not set (fallback data will be used)'}")
print(f"Search Query : {SEARCH_QUERY}")

def fetch_jobs(query, api_key, num_pages=2):
    """
    Fetches job listings from Google Jobs via SerpAPI.


    Parameters:
        query    (str) : The job search query (e.g. 'Data Engineer India')
        api_key  (str) : Your SerpAPI key
        num_pages(int) : Number of result pages to fetch (default: 2)


    Returns:
        list : A list of job dictionaries
    """
    all_jobs = []


    for page in range(num_pages):
        # API pagination: 'start' tells the API which result to start from
        # Page 0: results 0-9, Page 1: results 10-19, etc.
        params = {
            'engine'    : 'google_jobs',  # Use the Google Jobs search engine
            'q'         : query,
            'api_key'   : api_key,
            'hl'        : 'en',           # Language: English
            'start'     : page * 10       # Pagination offset
        }


        try:
            response = requests.get(SERP_URL, params=params, timeout=15)


            if response.status_code == 200:
                data = response.json()


                # 'jobs_results' is the key in the JSON that holds the job listings
                jobs = data.get('jobs_results', [])


                for job in jobs:
                    # Extract and normalize each job's fields
                    # .get('key', 'default') returns the value if the key exists,
                    # or 'default' if it does not — prevents KeyError crashes
                    all_jobs.append({
                        'title'      : job.get('title', 'Unknown Title'),
                        'company'    : job.get('company_name', 'Unknown Company'),
                        'location'   : job.get('location', 'Unknown Location'),
                        'posted'     : job.get('detected_extensions', {}).get('posted_at', 'Unknown'),
                        'salary'     : job.get('detected_extensions', {}).get('salary', 'Not Disclosed'),
                        'job_type'   : job.get('detected_extensions', {}).get('schedule_type', 'Not Specified'),
                        'description': job.get('description', '')[:300]  # First 300 characters only
                    })


                print(f"  Page {page + 1}: fetched {len(jobs)} jobs")
            else:
                print(f"  Page {page + 1}: API error {response.status_code}")


        except Exception as e:
            print(f"  Page {page + 1}: error — {e}")


    return all_jobs


# ── Actually call the function ────────────────────────────────
job_records = []


if SERP_API_KEY != 'YOUR_SERPAPI_KEY_HERE':
    print(f"Fetching job listings for: '{SEARCH_QUERY}'")
    job_records = fetch_jobs(SEARCH_QUERY, SERP_API_KEY)
    print(f"Total jobs fetched: {len(job_records)}")
else:
    print("No SerpAPI key provided — fallback job data will be loaded next.")