# -*- coding: utf-8 -*-
"""Day 2 Session + Mini project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-QM7B_MiqMnAzq6uZCHJKjkmQ3uFesl
"""

import sqlite3                   #create, query db

import pandas as pd              #dataframe

import matplotlib.pyplot as plt  #to plot / visulaize

import warnings                  #to generate precise error message

print("libraries installled successfully")

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv("student_performance.csv")

print(f"Dataset loaded :{df.shape[0]} students, {df.shape[1]} columns")
print(f"columns : {df.columns.to_list()}")

conn=sqlite3.connect("college.db")

cursor=conn.cursor()

df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

cursor.execute("SELECT COUNT(*) FROM students")

count=cursor.fetchone()[0]

print("database created")

print(f"Table'students' has {count} rows")

#PRAGMA
cursor.execute("PRAGMA table_info(students)")

columns=cursor.fetchall()

print("student table")

print(f"{'column':<25} {'data type':<12}")

for col in columns:
  print(f"{col[1]:25} {col[2]:11}")

def run_query(sql, description=""):
  if description:
    print(f"\n{'='*60}")
    print(f"{description}")
    print(f"{'='*60}")
  result=pd.read_sql_query(sql,conn)
  print(result.to_string(index=False))
  return result

query1="""
      SELECT student_id,name,department,math_score,attendance_percentage FROM students LIMIT 10
      """
result1=run_query(query1,"first 10 students")

query2="""
      SELECT student_id,name,department,math_score,attendance_percentage FROM students LIMIT 10 OFFSET 25
      """
result2=run_query(query1,"first 10 students")

query3="""SELECT student_id,name,department,programming_score FROM students WHERE programming_score>50 AND programming_score<75"""
result3=run_query(query3,"score btw 50 and 75")

query4="""SELECT student_id,name,department,programming_score FROM students WHERE programming_score BETWEEN 50 AND 75"""
result4=run_query(query4,"score btw 50 and 75")

query5="""SELECT department FROM students """
result5=run_query(query5,"")

query5="""SELECT student_id,name,department,MAX(programming_score) FROM students GROUP BY department ORDER BY MAX(programming_score) DESC LIMIT 1 """
result5=run_query(query5,"highest score of each deaprtment")

query6="""SELECT name,department,attendance_percentage FROM students WHERE attendance_percentage > 90 AND department != 'Civil' ORDER BY attendance_percentage DESC"""
result6=run_query(query6,"")

query7="""SELECT name,department,attendance_percentage FROM students WHERE NOT attendance_percentage > 80 ORDER BY attendance_percentage"""
result7=run_query(query7,"")

dept_data={
    'dept_code': ['CS','EC','ME','CE'],
    'dept_name':['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name': ['Dr.Sharma' ,'Dr. Reddy','Dr. patel', 'Dr. Kumar'],
    'established': [1985,1988,1972,1965],
    'intake': [60,60,60,60]
}
dept_df=pd.DataFrame(dept_data)

dept_df.to_sql(
    'departments',
    conn,
    if_exists='replace',
    index=False
)

dept_df.to_sql('departments',conn,if_exists='replace',index=False)

print("created 'departments' table :\n")

print(dept_df.to_string(index=False))

dept_map={
    'Computer Science':'CS',
    'Electronics':'EC',
    'Mechanical':'ME',
    'Civil':'CE'
}

df['dept_code']=df['department'].map(dept_map)

df.to_sql('students',conn,if_exists='replace',index=False)

print("\nupdated 'students' table")

query_join="""SELECT name,s.math_score,d.dept_name,d.hod_name,d.established FROM students s JOIN departments d ON s.dept_code=d.dept_code ORDER BY s.math_score DESC LIMIT 8 """
result_join=run_query(query_join,"")

query_append="""ALTER TABLE students ADD COLUMN department_code INT"""
cursor.execute(query_append)
conn.commit()
print("Column 'department_code' added to 'students' table.")

query_left_join="""SELECT name,s.math_score,d.dept_name,d.hod_name,d.established FROM students s LEFT JOIN departments d ON s.dept_code=d.dept_code"""
result_left_join=run_query(query_left_join,"")

query_right_join="""SELECT name,s.math_score,d.dept_name,d.hod_name,d.established FROM departments d LEFT JOIN students s ON s.dept_code=d.dept_code""" #right join not supported by sqlite
result_right_join=run_query(query_right_join,"")

chart1_sql="""SELECT department,ROUND(AVG(math_score),2) AS avg_math FROM students GROUP BY department ORDER BY avg_math DESC"""

chart1_data = pd.read_sql_query(chart1_sql,conn)

fix, ax=plt.subplots(figsize=(10,6))

bar=chart1_data.plot(kind='bar',x='department',y='avg_math',ax=ax)

"""### Question 1: Write a SQL query to find the average programming score for female students only."""

query1 = """
SELECT AVG(programming_score) AS avg_programming_score
FROM students
WHERE gender = 'Female';
"""

result1 = pd.read_sql_query(query1, conn)
print(result1)

"""### Question 2: What is the difference between WHERE and HAVING? Write one example of each using the students table."""

query_where = """
SELECT *
FROM students
WHERE attendance > 85;
"""

# HAVING:
# Used to filter grouped data AFTER GROUP BY

query_having = """
SELECT department, AVG(attendance) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance) > 85;
"""

"""### Question 3: Write a SQL query to find all departments where the average attendance is above 85%."""

query = "PRAGMA table_info(students);"

columns = pd.read_sql_query(query, conn)

print(columns)

query3 = """
SELECT department,
AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85;
"""

result3 = pd.read_sql_query(query3, conn)

print(result3)

"""### Question 4: What does pd.read_sql_query() return? What two arguments does it require?"""

# pd.read_sql_query() returns:
# -> A Pandas DataFrame

# It requires 2 arguments:
# 1. SQL query
# 2. Database connection object

# Example:
df = pd.read_sql_query("SELECT * FROM students", conn)

"""### Question 5: Modify Chart 1 (bar chart) to show average PROGRAMMING scores instead of math scores."""

import matplotlib.pyplot as plt
import pandas as pd

query5 = """
SELECT department,
AVG(programming_score) AS avg_programming
FROM students
GROUP BY department;
"""

df_prog = pd.read_sql_query(query5, conn)

plt.figure(figsize=(8,5))

plt.bar(
    df_prog['department'],
    df_prog['avg_programming'],
    color=['skyblue', 'teal', 'orange', 'purple']
)

plt.title("Avg Programming Score by Department")
plt.xlabel("Department")
plt.ylabel("Average Programming Score")

for i, value in enumerate(df_prog['avg_programming']):
    plt.text(i, value + 1, f"{value:.1f}", ha='center')

plt.show()

"""###Avg Math Score by Department"""

query1 = """
SELECT department,
AVG(math_score) AS avg_math
FROM students
GROUP BY department
"""

df1 = pd.read_sql_query(query1, conn)

plt.figure(figsize=(8,5))

plt.bar(
    df1['department'],
    df1['avg_math'],
    color=['skyblue', 'teal', 'orange', 'purple']
)

plt.title("Avg Math Score by Department")
plt.xlabel("Department")
plt.ylabel("Average Math Score")

# Show values on top of bars
for i, value in enumerate(df1['avg_math']):
    plt.text(i, value + 1, f"{value:.1f}", ha='center')

plt.show()

"""###Student Count by Department"""

query2 = """
SELECT department,
COUNT(*) AS total_students
FROM students
GROUP BY department
"""

df2 = pd.read_sql_query(query2, conn)

plt.figure(figsize=(7,7))

plt.pie(
    df2['total_students'],
    labels=df2['department'],
    autopct='%1.0f%%',
    startangle=90
)

plt.title("Students per Department")

plt.show()

"""###Top 8 Students by Total Score"""

query = "PRAGMA table_info(students);"

columns = pd.read_sql_query(query, conn)

print(columns[['name']])

query3 = """
SELECT name,
(math_score + programming_score+science_score+english_score) AS total_score
FROM students
ORDER BY total_score DESC
LIMIT 8
"""

df3 = pd.read_sql_query(query3, conn)

plt.figure(figsize=(9,6))

plt.barh(
    df3['name'],
    df3['total_score'],
    color='skyblue'
)

# Highest score at top
plt.gca().invert_yaxis()

plt.title("Top 8 Students — Total Score")
plt.xlabel("Total Score (out of 400)")
plt.ylabel("Students")

# Show values on bars
for i, value in enumerate(df3['total_score']):
    plt.text(value + 2, i, str(value), va='center')

plt.show()

"""###Avg Attendance by Gender"""

query4 = """
SELECT gender,
AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY gender
"""

df4 = pd.read_sql_query(query4, conn)

plt.figure(figsize=(7,5))

plt.bar(
    df4['gender'],
    df4['avg_attendance'],
    color=['skyblue', 'orange']
)

plt.title("Average Attendance by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Attendance (%)")

# Show values on top of bars
for i, value in enumerate(df4['avg_attendance']):
    plt.text(i, value + 1, f"{value:.1f}%", ha='center')

plt.show()